### ISSUE TITLE
Bolts 1.9.0 Compatibility

### ISSUE THREAD

**Issue by Steeve1995** [parse-community/ParseTwitterUtils-iOS#47]
Please make an update for the compatibility with the new version of Bolts.

**Comment by AmrKafina** [comment]
The master branch is compatible with the new version of Bolts; there just hasn't been any new releases. You can use `pod 'ParseTwitterUtils', git: 'https://github.com/parse-community/ParseTwitterUtils-iOS.git', branch: 'master'` in your podfile until then.
